### PR TITLE
Master2

### PR DESCRIPTION
**Pull request by Nemo2478**
Sb0t 5.41 are avaible.

### CODE REVIEW

**Comment by hollow87** [comment]
Why not use the default limits for max users, why limit it further?

**Comment by Nemo2478** [comment]
Because I saw some rooms that are working slow when more users are joining.

**Comment by hollow87** [comment]
Yes that is the case with single threaded poll/select server model.  However the changes you tried to implement can be done with a JS script.  Also your fork and branch does not compile without error as well.  A few other things to note.  Don't use a string where a number should be.  It's better to convert to a string less often than convert to a number more often.

**Comment by Nemo2478** [comment]
Hello hollow87,

are you refusing with this my modification?

**Comment by hollow87** [comment]
Yes as the changes you made can be done with a JS script.  Also you used a string to store a number and converted to a number when you needed it which is not a good practice.   It is better to store a number as a number and convert to a string when need be.

**Comment by Nemo2478** [comment]
Please show me how to determine the maximum of users with a JS Script and I will delete my Sb0t - Version and I will add new commands.

**Comment by hollow87** [comment]
Something similar to this.

```javascript
var userCount = 0;
var maxUsers = 60;
Users.local(function(userobj) {
  userCount++;
});

function onJoinCheck(userobj) {
  if(userCount + 1 > maxUsers)
    return false;
  userCount++;
  return true;
}

**Comment by Nemo2478** [comment]
Ohhh!! How helpful the posibility to write the own scripts in Sb0t!! 
Ok. I must to give my word. I deleted my Sb0t - Version everywhere!!

**Comment by hollow87** [comment]
You don't need to delete your versions, because of the reasons above I just won't merge into the official repository

**Pull request closed without merging**
